#!/usr/bin/env bash
# Archovive Open-Core installer — unpack v4 product bundle and wire ARCHOVIVE_ENGINE_ROOT.
set -euo pipefail

BUNDLE_NAME="archovive_product_bundle_v4.zip"
TARGET_DIR="archovive_product_bundle_v4"
CLI_ROOT="$(cd "$(dirname "$0")" && pwd)"

cd "${CLI_ROOT}"

echo "==> Archovive Installer (v4)"
echo "==> Erwartetes Bundle: ${BUNDLE_NAME}"
echo "==> Installationsverzeichnis: ${CLI_ROOT}"
echo

if ! command -v unzip >/dev/null 2>&1; then
  echo "FEHLER: unzip nicht gefunden. Bitte installieren (z. B. apt install unzip)."
  exit 1
fi

if [[ ! -f "${BUNDLE_NAME}" ]]; then
  echo "FEHLER: ${BUNDLE_NAME} nicht gefunden."
  echo "Bitte das Produkt-Bundle in dieses Verzeichnis legen:"
  echo "  ${CLI_ROOT}/"
  echo "Quelle (Engine / Bundle-Build): https://github.com/Archovive/Archovive-core"
  exit 1
fi

if [[ -d "${TARGET_DIR}" ]]; then
  echo "==> Entferne bestehende Installation: ${TARGET_DIR}"
  rm -rf "${TARGET_DIR}"
fi

echo "==> Entpacke ${BUNDLE_NAME} ..."
unzip -q "${BUNDLE_NAME}"

if [[ ! -d "${TARGET_DIR}" ]]; then
  echo "FEHLER: Bundle konnte nicht entpackt werden (Ordner ${TARGET_DIR} fehlt)."
  exit 1
fi

ENGINE_ROOT="${CLI_ROOT}/${TARGET_DIR}"
export ARCHOVIVE_ENGINE_ROOT="${ENGINE_ROOT}"
export ARCHOVIVE_REPO="${ENGINE_ROOT}"

echo "==> Setze ARCHOVIVE_ENGINE_ROOT:"
echo "    ${ENGINE_ROOT}"

ENV_FILE="${CLI_ROOT}/archovive.env"
cat > "${ENV_FILE}" <<EOF
# Generated by install_archovive.sh — source before using bin/archovive
export ARCHOVIVE_ENGINE_ROOT="${ENGINE_ROOT}"
export ARCHOVIVE_REPO="${ENGINE_ROOT}"
EOF
echo "==> Geschrieben: ${ENV_FILE}"
echo "    source ${ENV_FILE}"

BASHRC_LINE="export ARCHOVIVE_ENGINE_ROOT=\"${ENGINE_ROOT}\""
if [[ -f "${HOME}/.bashrc" ]] && ! grep -Fq "${BASHRC_LINE}" "${HOME}/.bashrc" 2>/dev/null; then
  echo "" >> "${HOME}/.bashrc"
  echo "# Archovive product bundle v4" >> "${HOME}/.bashrc"
  echo "${BASHRC_LINE}" >> "${HOME}/.bashrc"
  echo "==> ARCHOVIVE_ENGINE_ROOT in ~/.bashrc eingetragen"
else
  echo "==> ~/.bashrc unverändert (Zeile existiert bereits oder keine .bashrc)"
fi

if [[ -x "${ENGINE_ROOT}/install_archovive.sh" ]]; then
  echo "==> Bundle-Installer (venv) ..."
  (cd "${ENGINE_ROOT}" && ./install_archovive.sh "$@")
fi

if [[ -f "${ENGINE_ROOT}/bin/archovive" ]]; then
  mkdir -p "${HOME}/.local/bin"
  ln -sf "${ENGINE_ROOT}/bin/archovive" "${HOME}/.local/bin/archovive"
  echo "==> Symlink: ~/.local/bin/archovive -> ${ENGINE_ROOT}/bin/archovive"
else
  echo "WARNUNG: ${ENGINE_ROOT}/bin/archovive nicht gefunden."
  echo "Open-Core CLI: ${CLI_ROOT}/bin/archovive (ohne Engine-Funktionen)"
fi

echo
echo "==> Installation abgeschlossen."
echo "Neues Terminal oder:"
echo "    source ${ENV_FILE}"
echo
echo "Test:"
echo "    archovive --help"
echo "    archovive run /path/to/your-repo"
echo "    archovive evidence flask   # Evidence Camera (im Bundle)"
